export const GET_QUIZES_SUCCESS = 'GET_QUIZES_SUCCESS'
export const GET_QUIZES_ERROR = 'GET_QUIZES_ERROR'
export const TURN_ON_FETCHING = 'TURN_ON_FETCHING'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const SET_ANSWER_STATE = 'SET_ANSWER_STATE'
export const SET_QUIZ_FINISHED = 'SET_QUIZ_FINISHED'
export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION'
export const SET_NULL_QUIZ = 'SET_NULL_QUIZ'

export const ADD_QUESTION = 'ADD_QUESTION'
export const CREATE_QUIZ = 'CREATE_QUIZ'
export const SET_QUIZ_EMPTY = 'SET_QUIZ_EMPTY'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const LOGOUT = 'LOGOUT'